conda-forge/nbconvert-feedstock

- .circleci/build_steps.sh
- README.md
- recipe/meta.yaml
> Pin `pandoc` to suggested versions.

- recipe/meta.yaml
> Release 6.0.6

- recipe/meta.yaml
Checklist
Same as https://github.com/conda-forge/nbconvert-feedstock/pull/31 but for ppc64le
> Remove pandoc for ppc64le too

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_python3.6.____73_pypy.yaml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.6.____73_pypy.yaml
- .ci_support/linux_aarch64_python3.6.____cpython.yaml
- .ci_support/linux_aarch64_python3.7.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.6.____73_pypy.yaml
- .ci_support/linux_ppc64le_python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .drone.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .travis.yml
- README.md
- conda-forge.yml
- recipe/meta.yaml
> arm osx migrator

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
Checklist
I'm publishing the 6.2.0 release, and would like to publish an 6.2.0rc0 conda-forge package to match the pypi RC I just released. I think I need to be a contributor in order to create an RC branch for the 6.2.0rc0 package. I'd also like to help update this feedstock for the 6.2.0 final release.
> Add jasongrout to maintainers

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.7.____73_pypy.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.7.____73_pypy.yaml
- .ci_support/linux_aarch64_python3.7.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_python3.7.____73_pypy.yaml
- .ci_support/linux_ppc64le_python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> nbconvert 6.4.0

- LICENSE.txt
- recipe/meta.yaml
> Release 6.4.1

- recipe/meta.yaml
> Release 6.4.2

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Release 6.4.4

- README.md
- recipe/meta.yaml
> Release 6.4.5

- .circleci/config.yml
- .scripts/build_steps.sh
- LICENSE.txt
- build-locally.py
- recipe/meta.yaml
> Release 6.5.1

- recipe/meta.yaml
> Release 6.5.2

- recipe/meta.yaml
> Release 6.5.3

- recipe/meta.yaml
> nbconvert 7.3.0

- recipe/meta.yaml
Checklist
References:
- rerender for https://github.com/conda-forge/nbconvert-feedstock/issues/98
> bump build for staging promotion fail

- conda-forge.yml
- recipe/meta.yaml
> nbconvert 7.3.1

- recipe/meta.yaml
> nbconvert 7.6.0

- .ci_support/linux_64_.yaml
- recipe/meta.yaml
Checklist
References:
- https://github.com/jupyter/nbconvert/pull/2199
- https://github.com/conda-forge/mistune-feedstock/pull/37
> Pin mistune <3.1

- recipe/meta.yaml
Checklist
Changes:
- can be removed after https://github.com/conda-forge/bleach-feedstock/pull/42
> nbconvert 7.16.5

- recipe/meta.yaml
Checklist
References
- fixes #143 
- blocked by https://github.com/conda-forge/bleach-feedstock/pull/43
Changes:
- presently this is only available for a single, latest version, but will shift the burden from maintaining the pin here to where it's easier to fix, if needed, over on bleach-feedstock
> use bleach-with-css
